# Generated by Django 3.2.5 on 2022-09-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('ConversationID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=30)),
                ('LastMessage', models.DateTimeField()),
            ],
            options={
                'db_table': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryCode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('NotificationTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationTypeName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'NotificationTypes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=50, null=True)),
                ('Blurb', models.TextField(blank=True, null=True)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('Code', models.TextField(blank=True, null=True)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('UserConversationID', models.AutoField(primary_key=True, serialize=False)),
                ('DateJoined', models.DateTimeField()),
                ('LastViewed', models.DateTimeField(blank=True, null=True)),
                ('Conversation', models.ForeignKey(db_column='ConversationID', on_delete=django.db.models.deletion.RESTRICT, related_name='UserConversations', to='users.conversation')),
                ('UserProfile', models.ForeignKey(db_column='UserProfileID', on_delete=django.db.models.deletion.RESTRICT, related_name='UserConversations', to='users.userprofile')),
            ],
            options={
                'db_table': 'UserConversations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('NotificationDate', models.DateTimeField()),
                ('ViewedInd', models.BooleanField(default=False)),
                ('NotificationType', models.ForeignKey(db_column='NotificationTypeID', on_delete=django.db.models.deletion.RESTRICT, related_name='Notifications', to='users.notificationtype')),
                ('UserProfile', models.ForeignKey(db_column='UserProfileID', on_delete=django.db.models.deletion.RESTRICT, related_name='Notifications', to='users.userprofile')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Conversation', models.ForeignKey(db_column='ConversationID', on_delete=django.db.models.deletion.RESTRICT, related_name='Messages', to='users.conversation')),
                ('UserProfile', models.ForeignKey(db_column='UserProfileID', on_delete=django.db.models.deletion.RESTRICT, related_name='Messages', to='users.userprofile')),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conversation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='users.conversation')),
                ('Group', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
            ],
            options={
                'db_table': 'GroupConversations',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('UserProfileID', models.IntegerField()),
                ('DateConnected', models.DateField()),
                ('ContactProfile', models.ForeignKey(db_column='ContactProfileID', on_delete=django.db.models.deletion.RESTRICT, related_name='Contacts', to='users.userprofile')),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
    ]
