# Generated by Django 3.2.5 on 2022-09-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('BatchJobID', models.AutoField(primary_key=True, serialize=False)),
                ('BatchJobName', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('DeletedInd', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'BatchJobs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('ConditionID', models.IntegerField(primary_key=True, serialize=False)),
                ('ConditionName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Conditions',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('FileTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('FileTypeName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'FileTypes',
            },
        ),
        migrations.CreateModel(
            name='InputProfile',
            fields=[
                ('InputProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('InputProfileName', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('DeletedInd', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'InputProfiles',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.CharField(max_length=100)),
                ('JobDescription', models.TextField()),
                ('SubmittedAt', models.DateTimeField(auto_now=True)),
                ('FinishedAt', models.DateTimeField(blank=True, null=True)),
                ('BatchJobInd', models.BooleanField(default=False)),
                ('JobTypeID', models.IntegerField()),
                ('StatusID', models.IntegerField(blank=True, null=True)),
                ('NotificationMethod', models.CharField(blank=True, max_length=10, null=True)),
                ('NotificationURL', models.CharField(blank=True, max_length=255, null=True)),
                ('HttpStatusID', models.IntegerField(blank=True, null=True)),
                ('NotificationEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailStatusID', models.IntegerField(blank=True, null=True)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('BatchJobID', models.ForeignKey(blank=True, db_column='BatchJobID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='jobs.batchjob')),
            ],
            options={
                'db_table': 'Jobs',
                'ordering': ['-JobID'],
            },
        ),
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('JobStageID', models.AutoField(primary_key=True, serialize=False)),
                ('ToolName', models.CharField(blank=True, max_length=100, null=True)),
                ('Commands', models.TextField(blank=True, null=True)),
                ('RequiresEditInd', models.BooleanField(blank=True, default=False, null=True)),
                ('ExitCode', models.IntegerField(blank=True, default=None, null=True)),
                ('ClusterJobID', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('JobData', models.TextField(blank=True, null=True)),
                ('ErrorLog', models.CharField(blank=True, max_length=255, null=True)),
                ('OutputLog', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkingDirectory', models.CharField(blank=True, max_length=255, null=True)),
                ('Job', models.ForeignKey(db_column='JobID', on_delete=django.db.models.deletion.CASCADE, related_name='JobStages', to='jobs.job')),
            ],
            options={
                'db_table': 'JobStages',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('ParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('ParameterName', models.CharField(max_length=30)),
                ('Context', models.CharField(max_length=100)),
                ('InputBy', models.CharField(max_length=20)),
                ('Value', models.TextField()),
                ('Multiple', models.BooleanField(default=False)),
                ('Delimiter', models.CharField(blank=True, max_length=10, null=True)),
                ('ParameterIndex', models.CharField(max_length=7)),
                ('Optional', models.BooleanField(db_column='OptionalInd', default=False)),
                ('DeletedInd', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('ParameterTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ParameterTypeName', models.CharField(db_column='ParameterName', max_length=40)),
            ],
            options={
                'db_table': 'ParameterTypes',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('ReferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstNames', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=45)),
                ('Title', models.CharField(max_length=10)),
                ('Affiliation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'References',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('StageID', models.AutoField(db_column='WorkflowToolID', primary_key=True, serialize=False)),
                ('Checkpoint', models.BooleanField(default=False)),
                ('StageLevel', models.IntegerField(default=0)),
                ('left_co_ord', models.IntegerField()),
                ('top_co_ord', models.IntegerField()),
            ],
            options={
                'db_table': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('ToolID', models.AutoField(primary_key=True, serialize=False)),
                ('ToolName', models.CharField(max_length=30)),
                ('ToolDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('PublicInd', models.BooleanField(default=False)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, related_name='Tools', to='jobs.category')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('ToolVersionID', models.AutoField(primary_key=True, serialize=False)),
                ('ToolVersionNum', models.CharField(max_length=30)),
                ('ShortDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('LongDescription', models.TextField(blank=True, null=True)),
                ('Command', models.TextField()),
                ('DatePublished', models.DateField(auto_now=True)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('Tool', models.ForeignKey(db_column='ToolID', on_delete=django.db.models.deletion.CASCADE, related_name='ToolVersions', to='jobs.tool')),
            ],
            options={
                'db_table': 'ToolVersions',
                'ordering': ['-ToolVersionID'],
                'unique_together': {('Tool', 'ToolVersionNum')},
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('WorkflowID', models.AutoField(primary_key=True, serialize=False)),
                ('WorkflowName', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('PublicInd', models.BooleanField(default=False)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, related_name='Workflows', to='jobs.category')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('WorkflowVersionID', models.AutoField(primary_key=True, serialize=False)),
                ('WorkflowVersionNum', models.CharField(max_length=30)),
                ('ShortDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('LongDescription', models.TextField(blank=True, null=True)),
                ('DatePublished', models.DateField(auto_now=True)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('Workflow', models.ForeignKey(db_column='WorkflowID', on_delete=django.db.models.deletion.CASCADE, related_name='WorkflowVersions', to='jobs.workflow')),
            ],
            options={
                'db_table': 'WorkflowVersions',
                'unique_together': {('Workflow', 'WorkflowVersionNum')},
            },
        ),
        migrations.CreateModel(
            name='StageParameter',
            fields=[
                ('StageParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('StageParameterType', models.IntegerField(db_column='StageParameterTypeID')),
                ('Value', models.TextField()),
                ('Parameter', models.ForeignKey(db_column='ParameterID', on_delete=django.db.models.deletion.CASCADE, related_name='ParameterStages', to='jobs.parameter')),
                ('Stage', models.ForeignKey(db_column='StageID', on_delete=django.db.models.deletion.CASCADE, related_name='StageParameters', to='jobs.stage')),
            ],
            options={
                'db_table': 'StageParameters',
                'unique_together': {('Stage', 'Parameter')},
            },
        ),
        migrations.CreateModel(
            name='StageDependency',
            fields=[
                ('StageDependencyID', models.AutoField(primary_key=True, serialize=False)),
                ('ExitCodeValue', models.IntegerField(blank=True, null=True)),
                ('Condition', models.ForeignKey(db_column='ConditionID', on_delete=django.db.models.deletion.CASCADE, related_name='ConditionsStageDependencies', to='jobs.condition')),
                ('DependantOn', models.ForeignKey(db_column='DependantOnID', on_delete=django.db.models.deletion.CASCADE, related_name='ReliantStages', to='jobs.stage')),
                ('StageOI', models.ForeignKey(db_column='StageID', on_delete=django.db.models.deletion.CASCADE, related_name='StageDependencies', to='jobs.stage')),
            ],
            options={
                'db_table': 'StageDependencies',
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='SubWorkflowVersion',
            field=models.ForeignKey(blank=True, db_column='SubWorkflowVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkflowVersionWorkflows', to='jobs.workflowversion'),
        ),
        migrations.AddField(
            model_name='stage',
            name='ToolVersion',
            field=models.ForeignKey(blank=True, db_column='ToolVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToolVersionStages', to='jobs.toolversion'),
        ),
        migrations.AddField(
            model_name='stage',
            name='WorkflowVersion',
            field=models.ForeignKey(db_column='WorkflowVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='WorkflowVersionStages', to='jobs.workflowversion'),
        ),
        migrations.CreateModel(
            name='ParameterOption',
            fields=[
                ('ParameterOptionID', models.AutoField(primary_key=True, serialize=False)),
                ('ParameterOptionText', models.CharField(max_length=50)),
                ('ParameterOptionValue', models.CharField(max_length=30)),
                ('DeletedInd', models.BooleanField(default=False)),
                ('Parameter', models.ForeignKey(db_column='ParameterID', on_delete=django.db.models.deletion.CASCADE, related_name='ParameterOptions', to='jobs.parameter')),
            ],
            options={
                'db_table': 'ParameterOptions',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='ParameterType',
            field=models.ForeignKey(db_column='ParameterTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='Parameters', to='jobs.parametertype'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='ParentParameter',
            field=models.ForeignKey(blank=True, db_column='ParentParameterID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChildParameters', to='jobs.parameter'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='ToolVersion',
            field=models.ForeignKey(db_column='ToolVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='ToolParameters', to='jobs.toolversion'),
        ),
        migrations.CreateModel(
            name='JobStageParameter',
            fields=[
                ('JobStageParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('ParameterName', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Value', models.TextField()),
                ('JobStage', models.ForeignKey(db_column='JobStageID', on_delete=django.db.models.deletion.CASCADE, related_name='JobStageParameters', to='jobs.jobstage')),
                ('Parameter', models.ForeignKey(db_column='ParameterID', on_delete=django.db.models.deletion.CASCADE, related_name='ParameterJobTools', to='jobs.parameter')),
                ('StageParameter', models.ForeignKey(blank=True, db_column='StageParameterID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StageParameterInstances', to='jobs.stageparameter')),
            ],
            options={
                'db_table': 'JobStageParameters',
            },
        ),
        migrations.CreateModel(
            name='JobStageDependency',
            fields=[
                ('JobStageDependencyID', models.AutoField(primary_key=True, serialize=False)),
                ('ExitCodeValue', models.IntegerField(blank=True, null=True)),
                ('Condition', models.ForeignKey(db_column='ConditionID', on_delete=django.db.models.deletion.CASCADE, related_name='ConditionsJobStageDependencies', to='jobs.condition')),
                ('DependantOn', models.ForeignKey(db_column='DependantOnID', on_delete=django.db.models.deletion.CASCADE, related_name='ReliantJobStages', to='jobs.jobstage')),
                ('JobStageOI', models.ForeignKey(db_column='JobStageID', on_delete=django.db.models.deletion.CASCADE, related_name='JobStageDependencies', to='jobs.jobstage')),
            ],
            options={
                'db_table': 'JobStageDependencies',
            },
        ),
        migrations.CreateModel(
            name='JobStageDataSection',
            fields=[
                ('DataSectionID', models.AutoField(primary_key=True, serialize=False)),
                ('DataSectionName', models.CharField(max_length=30)),
                ('JobStage', models.ForeignKey(db_column='JobStageID', on_delete=django.db.models.deletion.CASCADE, related_name='DataSections', to='jobs.jobstage')),
            ],
            options={
                'db_table': 'JobStageDataSections',
            },
        ),
        migrations.AddField(
            model_name='jobstage',
            name='Stage',
            field=models.ForeignKey(blank=True, db_column='StageID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StageJobs', to='jobs.stage'),
        ),
        migrations.AddField(
            model_name='jobstage',
            name='Status',
            field=models.ForeignKey(blank=True, db_column='StatusID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StatusJobStages', to='jobs.status'),
        ),
        migrations.AddField(
            model_name='job',
            name='ToolVersion',
            field=models.ForeignKey(blank=True, db_column='ToolVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToolVersionJobs', to='jobs.toolversion'),
        ),
        migrations.AddField(
            model_name='job',
            name='User',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='WorkflowVersion',
            field=models.ForeignKey(blank=True, db_column='WorkflowVersionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WorkflowVersionJobs', to='jobs.workflowversion'),
        ),
        migrations.CreateModel(
            name='InputProfileParameter',
            fields=[
                ('InputProfileParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.TextField(blank=True, null=True)),
                ('InputProfile', models.ForeignKey(db_column='InputProfileID', on_delete=django.db.models.deletion.CASCADE, related_name='InputProfileParameters', to='jobs.inputprofile')),
                ('Parameter', models.ForeignKey(db_column='ParameterID', on_delete=django.db.models.deletion.CASCADE, related_name='InputProfileParameters', to='jobs.parameter')),
            ],
            options={
                'db_table': 'InputProfileParameters',
            },
        ),
        migrations.AddField(
            model_name='inputprofile',
            name='WorkflowVersion',
            field=models.ForeignKey(db_column='WorkflowVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='InputProfiles', to='jobs.workflowversion'),
        ),
        migrations.CreateModel(
            name='ExpectedOutput',
            fields=[
                ('ExpectedOutputID', models.AutoField(primary_key=True, serialize=False)),
                ('OutputName', models.CharField(max_length=60)),
                ('FileName', models.CharField(max_length=256)),
                ('FileType', models.ForeignKey(db_column='FileTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='FileOutputs', to='jobs.filetype')),
                ('ToolVersion', models.ForeignKey(db_column='ToolVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='ExpectedOutputs', to='jobs.toolversion')),
            ],
            options={
                'db_table': 'ExpectedOutputs',
            },
        ),
        migrations.CreateModel(
            name='WorkflowReference',
            fields=[
                ('WorkflowReferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Reference', models.ForeignKey(db_column='ReferenceID', on_delete=django.db.models.deletion.CASCADE, related_name='ReferenceWorkflows', to='jobs.reference')),
                ('Workflow', models.ForeignKey(db_column='ToolID', on_delete=django.db.models.deletion.CASCADE, related_name='WorkflowReferences', to='jobs.workflow')),
            ],
            options={
                'db_table': 'WorkflowReferences',
                'unique_together': {('Workflow', 'Reference')},
            },
        ),
        migrations.CreateModel(
            name='UserWorkflowPermission',
            fields=[
                ('UserWorkflowPermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('Run', models.BooleanField(default=True)),
                ('Export', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Publish', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Workflow', models.ForeignKey(db_column='WorkflowID', on_delete=django.db.models.deletion.CASCADE, related_name='UserWorkflowPermissions', to='jobs.workflow')),
            ],
            options={
                'db_table': 'UserWorkflowPermissions',
                'unique_together': {('User', 'Workflow')},
            },
        ),
        migrations.CreateModel(
            name='UserToolPermission',
            fields=[
                ('UserToolPermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('Run', models.BooleanField(default=True)),
                ('Export', models.BooleanField(default=False)),
                ('Edit', models.BooleanField(default=False)),
                ('Publish', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('Tool', models.ForeignKey(db_column='ToolID', on_delete=django.db.models.deletion.CASCADE, related_name='UserToolPermissions', to='jobs.tool')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserToolPermissions',
                'unique_together': {('User', 'Tool')},
            },
        ),
        migrations.CreateModel(
            name='UserJobPermission',
            fields=[
                ('UserJobPermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('View', models.BooleanField(default=True)),
                ('Repeat', models.BooleanField(default=False)),
                ('Share', models.BooleanField(default=False)),
                ('Admin', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(db_column='JobID', on_delete=django.db.models.deletion.CASCADE, related_name='UserJobPermissions', to='jobs.job')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserJobPermissions',
                'unique_together': {('User', 'Job')},
            },
        ),
        migrations.CreateModel(
            name='ToolVersionResource',
            fields=[
                ('ToolVersionResourceID', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceManager', models.CharField(max_length=30)),
                ('Key', models.CharField(max_length=15)),
                ('Value', models.CharField(max_length=255)),
                ('Label', models.CharField(max_length=100)),
                ('ToolVersion', models.ForeignKey(db_column='ToolVersionID', on_delete=django.db.models.deletion.CASCADE, related_name='Resources', to='jobs.toolversion')),
            ],
            options={
                'db_table': 'ToolVersionResources',
                'unique_together': {('ResourceManager', 'ToolVersion', 'Key')},
            },
        ),
        migrations.CreateModel(
            name='ToolReference',
            fields=[
                ('ToolReferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Reference', models.ForeignKey(db_column='ReferenceID', on_delete=django.db.models.deletion.CASCADE, related_name='ReferenceTools', to='jobs.reference')),
                ('Tool', models.ForeignKey(db_column='ToolID', on_delete=django.db.models.deletion.CASCADE, related_name='ToolReferences', to='jobs.tool')),
            ],
            options={
                'db_table': 'ToolReferences',
                'unique_together': {('Tool', 'Reference')},
            },
        ),
        migrations.CreateModel(
            name='JobStageResource',
            fields=[
                ('JobStageResourceID', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceManager', models.CharField(max_length=30)),
                ('Key', models.CharField(max_length=15)),
                ('Value', models.CharField(max_length=255)),
                ('Label', models.CharField(max_length=100)),
                ('JobStage', models.ForeignKey(db_column='JobStageID', on_delete=django.db.models.deletion.CASCADE, related_name='JobStageResources', to='jobs.jobstage')),
            ],
            options={
                'db_table': 'JobStageResources',
                'unique_together': {('ResourceManager', 'JobStage', 'Key')},
            },
        ),
        migrations.CreateModel(
            name='JobStageDataField',
            fields=[
                ('DataFieldID', models.AutoField(primary_key=True, serialize=False)),
                ('Key', models.CharField(max_length=45)),
                ('Value', models.TextField()),
                ('Label', models.CharField(max_length=100)),
                ('ValueType', models.IntegerField()),
                ('JobStageDataSection', models.ForeignKey(db_column='DataSectionID', on_delete=django.db.models.deletion.CASCADE, related_name='DataFields', to='jobs.jobstagedatasection')),
            ],
            options={
                'db_table': 'JobStageDataFields',
                'unique_together': {('JobStageDataSection', 'Key')},
            },
        ),
    ]
