# Generated by Django 3.2.5 on 2022-09-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeDirectory', models.TextField(default='/')),
                ('AceTheme', models.CharField(default='chrome', max_length=30)),
                ('FontSize', models.IntegerField(default=11)),
                ('ServerPass', models.CharField(blank=True, max_length=1024, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FileManagerSettings',
            },
        ),
    ]
